### ISSUE TITLE
Mobile Wallet: Prepare for first Release

### ISSUE THREAD

**Issue by CortecKYC** [SelfKeyFoundation/identity-wallet-mobile#242]
- [x] All critical bugs fixed
- [x] Discuss QA strategy with @rhdelima to make sure all critical bugs have been tested and fixed by Thursday 27. the app is ready to be submitted to App Store on Friday 28
- [x] Submit mobile wallet to App Store on Friday 28
- [x] Once we get the approval, discuss with the rest of the team when exactly we'll launch (day and time)

Aha! Link: https://kycc.aha.io/features/MOBILE-135
